import os
from utils_agent import initiate_chat_with_retry
from config import FLAGS
from FVEval.fv_eval import utils as utils2
import re
from typing import Dict, List, Tuple
import networkx as nx
from pyverilog.vparser.parser import parse
from pyverilog.vparser.ast import (
    ModuleDef,
    Portlist,
    Port,
    Input,
    Output,
    Inout,
    Ioport,
    Wire,
    Reg,
    Instance,
)
from pyverilog.vparser.ast import Input, Output, Inout, Decl
from pyverilog.vparser.ast import Parameter, Localparam, Decl
from config import FLAGS
from saver import saver


def generate_comments(agents, design_code: str) -> str:
    """
    Generate comments for the design code using the Comment_Generation agent.

    Args:
        agents (dict): A dictionary of agents, including 'Comment_Generation'.
        design_code (str): The original design code to generate comments for.

    Returns:[]
        str: The design code with comments generated by the agent.
    """
    # Prepare the prompt by replacing the placeholder with the actual design code
    design_comment_generation = """
Please analyze the following RTL design code by commenting on each line and block directly within the code. Focus on extracting key features, functionalities, and signal interactions to help generate reliable assumptions and assertions. Provide clear and detailed explanations for how each part of the code contributes to the overall design. The comments should be included within the `verilog` block wrapping.

Input Design Code:
design_code_PH

Answer:
"""
    # Wrap the design code to preserve formatting and indicate the language
    wrapped_design_code = f"```verilog\n{design_code}\n```"

    # Replace the placeholder with the actual design code
    prompt_with_design = design_comment_generation.replace('design_code_PH', wrapped_design_code)

    # Use the Comment_Generation agent to generate the commented design code
    commented_design_response = initiate_chat_with_retry(
        agents["user"],
        agents["Comment_Generation"],
        message=prompt_with_design
    )

    # Parse the response to extract the commented code
    commented_design_code = utils2.parse_code_response_verilog(commented_design_response)

    return commented_design_code

# def generate_feature_tree(agents, design_code)

def preprocess_design(agents, design_code: str) -> str:
    """
    Preprocess the design code by adding comments using the Comment_Generation agent.

    Args:
        agents (dict): A dictionary of agents, including 'Comment_Generation'.
        design_code (str): The original design code to preprocess.

    Returns:
        str: The commented design code.
    """
    if FLAGS.add_comment:
        # Call the generate_comments function to add comments
        commented_design_code = generate_comments(agents, design_code)
        return commented_design_code
    elif FLAGS.use_ICRL:
        # If no preprocessing is needed, return the original design code
        design_meta = generate_line_block_spec(agents, design_code)
        return design_meta
    else:
        return design_code

# def generate_ast_with_llm(agents, design_code: str) -> str:
#     """
#     Generate an AST for the RTL code using an LLM agent, formatted to match iverilog's output.
    
#     Args:
#         agents (dict): A dictionary of agents, including 'AST_Generation'.
#         design_code (str): The RTL code to generate the AST from.
    
#     Returns:
#         str: A formatted AST string matching iverilog's output format.
#     """
#     # Prepare the prompt for the LLM
#     ast_prompt = f"""
# Please analyze the following Verilog RTL design code and generate its Abstract Syntax Tree (AST) representation.

# **Requirements:**
# - The AST must follow the exact structure and formatting used by iverilog's AST generation.
# - Include all relevant nodes, their types, names, and attributes as per iverilog's AST output.
# - Use indentation to represent the hierarchical structure.
# - Do not add any extra explanations or comments; only provide the AST.

# **Example of iverilog AST output:**
# Source Description ModuleDef (name: my_module) Paramlist Parameter (name: WIDTH, value: 8) Portlist Ioport Input (name: clk) Ioport Input (name: reset) Ioport Output (name: out_signal) Decl (type: wire, name: internal_signal) Always SensList Edge (type: posedge) Identifier (name: clk) Block IfStatement Condition Identifier (name: reset) TrueBranch NonBlockingSubstitution Lvalue Identifier (name: out_signal) Rvalue IntConst (value: 0) FalseBranch NonBlockingSubstitution Lvalue Identifier (name: out_signal) Rvalue Identifier (name: internal_signal) ...

# **Input Design Code:**
# ```verilog
# {design_code}

# Please provide the AST below:
# """

# # Call the LLM agent for AST generation 
# ast_response = initiate_chat_with_retry( agents["user"], agents["AST_Generation"], message=ast_prompt )

# # Assuming the response is the formatted AST
# formatted_ast = ast_response.strip()

# return formatted_ast


# def generate_ast_with_iverilog(design_code: str) -> str:
#     """
#     Generate an AST for the RTL code using PyVerilog (iverilog).

#     Args:
#         design_code (str): The RTL code to generate the AST from.

#     Returns:
#         str: A formatted AST string.
#     """
#     # Save the design code to a temporary file for parsing
#     temp_filename = "temp_design.v"
#     with open(temp_filename, "w") as temp_file:
#         temp_file.write(design_code)

#     # Parse the design code and extract the AST
#     try:
#         ast, _ = parse([temp_filename])
#         formatted_ast = format_ast(ast)
#     except Exception as e:
#         formatted_ast = f"Error parsing RTL code: {e}"
#     finally:
#         # Remove the temporary file after parsing
#         os.remove(temp_filename)

#     return formatted_ast

# def format_ast(node: Node, depth: int = 0) -> str:
#     """Recursively format the AST node into a readable string.
    
#     Args:
#         node (Node): The AST node.
#         depth (int): The current depth for formatting.

#     Returns:
#         str: A formatted string representation of the AST.
#     """
#     indent = "  " * depth
#     # Rest of your function logic goes here

#     # Include the node's name if it has one
#     if hasattr(node, 'name') and node.name:
#         node_info += f" (name: {node.name})"

#     # Recursively process child nodes
#     if hasattr(node, 'children') and node.children():
#         children_info = ""
#         for child in node.children():
#             children_info += "\n" + format_ast(child, depth + 1)
#         return f"{node_info}{children_info}"
#     else:
#         return node_info

# def generate_ast(agents, design_code: str, add_AST: bool = False) -> str: """ Generate an AST for the RTL code using the specified method.
#         Args:
#         agents (dict): A dictionary of agents, including 'AST_Generation' (if LLM method is used).
#         design_code (str): The RTL code to generate the AST from.
#         add_AST (bool): Flag to determine if AST generation is required.
#         AST_method (str): The method for generating the AST ('LLM' or 'iverilog').

#     Returns:
#         str: A formatted AST string.
#     """
#     if not add_AST:
#         return ""

#     if FLAGS.AST_method == "LLM":
#         return generate_ast_with_llm(agents, design_code)
#     elif FLAGS.AST_method == "iverilog":
#         return generate_ast_with_iverilog(design_code)
#     else:
#         raise ValueError("Invalid AST generation method. Choose 'LLM' or 'iverilog'.")


def generate_line_block_spec(agents, design_code: str) -> Dict:
    """
    Get simple block and line specifications using LLM.
    """
    specs_prompt = """
    Analyze this design code and identify:
    1. Important code blocks (modules, always blocks, FSMs, etc.) with their line ranges
    2. Critical individual lines (state changes, key assignments, etc.)

    Provide output in this JSON format:
    ```json
    {
        "blocks": [
            {
                "location": "10-20",
                "description": "Main FSM controller block implementing protocol handshake. Controls ready/valid signaling and handles backpressure. Key signals include ready, valid, and state transitions.",
                "code": "actual_code_snippet"
            }
        ],
        "lines": [
            {
                "location": "15",
                "description": "Critical state transition from IDLE to BUSY based on valid signal assertion. Controls the start of new transaction processing.",
                "code": "actual_line_code"
            }
        ]
    }
    ```

    Design Code:
    ```verilog
    {code}
    ```
    """

    # Get specifications from LLM
    specs_response = initiate_chat_with_retry(
        agents["user"],
        agents["Design_Meta"],
        message=specs_prompt.format(code=design_code)
    )
        
    # Extract and parse JSON
    try:
        specs_match = re.search(r'```json\s*(.*?)\s*```', specs_response, re.DOTALL)
        if specs_match:
            specs = json.loads(specs_match.group(1))
            return {
                "code": design_code,
                "blocks": process_blocks(specs["blocks"], design_code),
                "lines": process_lines(specs["lines"], design_code)
            }
    except Exception as e:
        print(f"Error processing LLM response: {e}")
        return {"code": design_code, "blocks": [], "lines": []}

def process_blocks(blocks: List[Dict], code: str) -> List[Dict]:
    """Process block specifications and add code snippets."""
    processed = []
    code_lines = code.splitlines()
    
    for block in blocks:
        try:
            start, end = map(int, block["location"].split("-"))
            if 1 <= start <= end <= len(code_lines):
                processed.append({
                    "location": block["location"],
                    "description": block["description"],
                    "code": "\n".join(code_lines[start-1:end])
                })
        except (ValueError, KeyError) as e:
            print(f"Error processing block: {e}")
            
    return processed

def process_lines(lines: List[Dict], code: str) -> List[Dict]:
    """Process line specifications and add code snippets."""
    processed = []
    code_lines = code.splitlines()
    
    for line in lines:
        try:
            line_num = int(line["location"])
            if 1 <= line_num <= len(code_lines):
                processed.append({
                    "location": line["location"],
                    "description": line["description"],
                    "code": code_lines[line_num-1].strip()
                })
        except (ValueError, KeyError) as e:
            print(f"Error processing line: {e}")
            
    return processed